config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: "auth", controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions"
    # passwords: "users/passwords" #,
    # omniauth_callbacks: "users/omniauth_callbacks"
  }, path_names: {
    sign_in: 'login',
    sign_up: 'signup',
    sign_out: 'logout'
  }, sign_out_via: [:get, :post, :delete]

  resources :short_hands do
    collection do
      get :autocomplete
    end
  end

  devise_scope :user do
    authenticated  do
      root to: "short_hands#new", as: 'authenticated_root'
    end
  end

  root to: "users/sessions#new"
end

app/models/short_hand.rb
class ShortHand < ApplicationRecord
  include Mongoid::Document
  include Mongoid::Timestamps

  searchkick word: [:description, :code], highlight: [:description, :code], suggest: [:description, :code]

  belongs_to :user
  has_many   :comments

  # General Information
  field :description, type: String
  field :tags, type: String
  field :code, type: String
  field :language, type: String

  validates :description, :tags, :language, :code, presence: true

  def owner? id
    user_id == id
  end

  def search_data
    {
      description: description,
      tags: tags,
      code: code,
      language: language,
      updated_at: updated_at
    }
  end

  def self._search params, aggs = [], per_page = 20
    search_text = "*"
    where = {}
    operator = "or"
    order = {_score: :desc}
    if params[:facets].present?
      fparam = params[:facets]
      search_text = fparam[:search] if fparam[:search].present?
      if fparam[:sort].present?
        order = {}
        order[fparam[:sort]] = :desc
      end

      where[:language] = fparam[:language] if fparam[:language].present?
      operator = "and" if fparam[:whole].present?
    end

    self.search search_text, operator: operator,
      fields: ["description^10", "code"],
      page: params[:page], per_page: per_page,
      order: order, misspellings: {below: 5},
      highlight: true, suggest: true,
      where: where, aggs: aggs #, smart_aggs: false
  end

  def self.autocomplete params
    self.search(params[:query], {
      fields: ["description^10", "code"],
      match: :word,
      limit: 10,
      load: false,
      misspellings: {below: 5}
    }).map(&:description)
  end
end

app/controllers/short_hands_controller.rb
class ShortHandsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :update, :destroy]
  before_action :set_shorthand, only: [:show, :edit, :update, :destroy]

  # GET /shorthands
  # GET /shorthands.json
  def index
    @shorthands = ShortHand._search(params, [], 10)
  end

  # GET /shorthands/1
  # GET /shorthands/1.json
  def show
  end

  def autocomplete
    render json: ShortHand.autocomplete(params)
  end

  # GET /shorthands/new
  def new
    @shorthand = ShortHand.new
  end

  # GET /shorthands/1/edit
  def edit
  end

  # POST /shorthands
  # POST /shorthands.json
  def create
    @shorthand = ShortHand.new(gist_params)
    @shorthand.user = current_user

    respond_to do |format|
      if @shorthand.save
        format.html { redirect_to short_hands_url, notice: 'Shorthand was successfully created.' }
        format.json { render :show, status: :created, location: @gist }
      else
        format.html { render :new }
        format.json { render json: @shorthand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shorthands/1
  # PATCH/PUT /shorthands/1.json
  def update
    respond_to do |format|
      if @shorthand.update(gist_params)
        format.html { redirect_to short_hands_url, notice: 'Shorthand was successfully updated.' }
        format.json { render :show, status: :ok, location: @gist }
      else
        format.html { render :edit }
        format.json { render json: @shorthand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shorthands/1
  # DELETE /shorthands/1.json
  def destroy
    @shorthand.destroy
    respond_to do |format|
      format.html { redirect_to short_hands_url, notice: 'Shorthand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shorthand
      @shorthand = ShortHand.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gist_params
      params.require(:short_hand).permit(:description, :tags, :code, :language)
    end
end

app/views/short_hands/_form.html.erb
<% content_for :head do %>
  <%= javascript_include_tag "editor" %>
<% end %>

<%= simple_form_for(shorthand) do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :description, placeholder: "", input_html: {class: "form-control"}, required: true %>
  </div>

  <div class="form-group">
    <%= f.input :language, collection: language_options, prompt: "Select language", input_html: { class: "form-control" }, required: true %>
  </div>

  <div class="form-group">
    <%= f.input :tags, input_html: { class: "form-control", data: { role: 'tagsinput' } }, required: true %>
  </div>

  <div class="form-group">
    <%= f.input :code, as: :ckeditor, required: true %>
  </div>

  <div class="form-group">
    <%= f.button :submit, name: "Submit", value: "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/short_hands/_gist.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><%></div>
  <div class="panel-body">
    <p>...</p>
  </div>
</div>

app/views/short_hands/edit.html.erb
<h1>Editing Short Hand</h1>

<%= render 'form', shorthand: @shorthand %>

<%= link_to 'Show', @shorthand %> |
<%= link_to 'Back', short_hands_path %>

app/views/short_hands/index.html.erb
<% title "Short Hands" %>
<% @shorthands.each do |shorthand| %>
  <div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">
      <%= link_to shorthand.description, shorthand %>
      <% if user_signed_in? %>
      <div class="pull-right">
        <%= link_to 'Edit', edit_short_hand_path(shorthand) if shorthand.owner?(current_user.try(:id)) %>
        <%= link_to '| Destroy', shorthand, method: :delete, data: { confirm: 'Are you sure?' } if shorthand.owner?(current_user.try(:id)) %>
      </div>
      <% end %>
    </div>
    <div class="panel-body">
      <% read_more = link_to "...Read more", shorthand %>
      <%= truncate_html(shorthand.code.html_safe, length: 300, word_boundary: false, omission: "<br><br> #{read_more}")%>
    </div>
  </div>
<% end %>

<div class="pages col-md-12 col-xs-12">
	<center><%#= paginate @shorthands, window: 2 %></center>
</div>

<%= link_to 'Create a new shorthand', new_short_hand_path, class: "btn btn-primary" %>

app/views/short_hands/new.html.erb
<% title "Create a new Short Hand" %>
<%= render 'form', shorthand: @shorthand if user_signed_in? %>
<% unless user_signed_in? %>
  <center>
    <a href="#" class="btn btn-primary"> Sign In with Google </a>
  </center>
<% end %>

app/views/short_hands/show.html.erb
<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading">
    <% if user_signed_in? %>
    <div class="pull-right">
      <%= link_to 'Edit', edit_short_hand_path(@shorthand) if @shorthand.owner?(current_user.try(:id)) %>
      <%= link_to '| Destroy', @shorthand, method: :delete, data: { confirm: 'Are you sure?' } if @shorthand.owner?(current_user.try(:id)) %>
    </div>
    <% end %>
    <strong><%= @shorthand.description %> </strong>
    <br>
    <%= "#{time_ago_in_words(@shorthand.created_at)} ago" %>
  </div>
  <div class="panel-body">
    <%= @shorthand.code.html_safe %>
  </div>
</div>

<%= link_to 'Back', short_hands_path, class: "btn btn-primary" %>